import { TimelineEvent, TimelinePeriod } from '@/types';

// Sample historical events data
export const sampleTimelineEvents: TimelineEvent[] = [
  {
    id: 'event_1',
    title: '大金字塔建造',
    date: '-2580-01-01',
    year: -2580,
    description: '古埃及第四王朝法老胡夫的陵墓，古代世界七大奇迹中唯一现存的建筑。',
    category: '古代建筑',
    importance: 'high',
    location: '埃及吉萨',
    figures: ['胡夫法老', '海米乌努'],
    relatedCards: [],
  },
  {
    id: 'event_2',
    title: '汉武帝即位',
    date: '-141-01-01',
    year: -141,
    description: '西汉第七位皇帝，在位期间开疆拓土，文治武功并举，开创了汉朝的鼎盛时期。',
    category: '政治变革',
    importance: 'high',
    location: '中国长安',
    figures: ['汉武帝刘彻', '卫青', '霍去病'],
    relatedCards: [],
  },
  {
    id: 'event_3',
    title: '罗马帝国建立',
    date: '-27-01-01',
    year: -27,
    description: '屋大维被元老院授予"奥古斯都"称号，标志着罗马共和国向罗马帝国的转变。',
    category: '政治变革',
    importance: 'high',
    location: '意大利罗马',
    figures: ['奥古斯都', '马克·安东尼', '克利奥帕特拉'],
    relatedCards: [],
  },
  {
    id: 'event_4',
    title: '耶稣诞生',
    date: '0001-01-01',
    year: 1,
    description: '基督教创始人耶稣基督的诞生，后来成为公元纪年的起点。',
    category: '宗教',
    importance: 'high',
    location: '巴勒斯坦伯利恒',
    figures: ['耶稣基督', '圣母玛利亚', '约瑟'],
    relatedCards: [],
  },
  {
    id: 'event_5',
    title: '罗马帝国分裂',
    date: '395-01-01',
    year: 395,
    description: '狄奥多西一世死后，罗马帝国正式分裂为东西两部分。',
    category: '政治变革',
    importance: 'high',
    location: '罗马帝国',
    figures: ['狄奥多西一世', '阿卡狄乌斯', '霍诺里乌斯'],
    relatedCards: [],
  },
  {
    id: 'event_6',
    title: '唐朝建立',
    date: '618-01-01',
    year: 618,
    description: '李渊建立唐朝，定都长安，开启了中国历史上的黄金时代。',
    category: '政治变革',
    importance: 'high',
    location: '中国长安',
    figures: ['李渊', '李世民', '李建成'],
    relatedCards: [],
  },
  {
    id: 'event_7',
    title: '查理曼加冕',
    date: '800-12-25',
    year: 800,
    description: '查理曼在罗马被教皇利奥三世加冕为"罗马皇帝"，标志着神圣罗马帝国的开始。',
    category: '政治变革',
    importance: 'high',
    location: '意大利罗马',
    figures: ['查理曼大帝', '教皇利奥三世'],
    relatedCards: [],
  },
  {
    id: 'event_8',
    title: '宋朝建立',
    date: '960-01-01',
    year: 960,
    description: '赵匡胤通过陈桥兵变建立宋朝，结束了五代十国的分裂局面。',
    category: '政治变革',
    importance: 'high',
    location: '中国开封',
    figures: ['宋太祖赵匡胤'],
    relatedCards: [],
  },
  {
    id: 'event_9',
    title: '十字军东征开始',
    date: '1095-11-27',
    year: 1095,
    description: '教皇乌尔班二世发起第一次十字军东征，目标是夺回耶路撒冷。',
    category: '宗教战争',
    importance: 'high',
    location: '法国克莱蒙',
    figures: ['教皇乌尔班二世', '戈德弗里'],
    relatedCards: [],
  },
  {
    id: 'event_10',
    title: '蒙古帝国建立',
    date: '1206-01-01',
    year: 1206,
    description: '铁木真统一蒙古草原，建立大蒙古国，被尊为成吉思汗。',
    category: '政治变革',
    importance: 'high',
    location: '蒙古草原',
    figures: ['成吉思汗铁木真'],
    relatedCards: [],
  },
  {
    id: 'event_11',
    title: '黑死病大流行',
    date: '1347-01-01',
    year: 1347,
    description: '鼠疫在欧洲大流行，导致欧洲人口锐减三分之一到一半。',
    category: '灾难事件',
    importance: 'high',
    location: '欧洲',
    figures: [],
    relatedCards: [],
  },
  {
    id: 'event_12',
    title: '文艺复兴开始',
    date: '1400-01-01',
    year: 1400,
    description: '以意大利为中心的文艺复兴运动，重新发现古希腊罗马文化。',
    category: '文化运动',
    importance: 'high',
    location: '意大利佛罗伦萨',
    figures: ['达芬奇', '米开朗基罗', '拉斐尔'],
    relatedCards: [],
  },
  {
    id: 'event_13',
    title: '哥伦布发现美洲',
    date: '1492-10-12',
    year: 1492,
    description: '克里斯托弗·哥伦布到达美洲，开启了欧洲殖民美洲的时代。',
    category: '地理发现',
    importance: 'high',
    location: '加勒比海',
    figures: ['克里斯托弗·哥伦布'],
    relatedCards: [],
  },
  {
    id: 'event_14',
    title: '宗教改革开始',
    date: '1517-10-31',
    year: 1517,
    description: '马丁·路德发表《九十五条论纲》，开启了宗教改革运动。',
    category: '宗教改革',
    importance: 'high',
    location: '德国维滕堡',
    figures: ['马丁·路德'],
    relatedCards: [],
  },
  {
    id: 'event_15',
    title: '工业革命开始',
    date: '1760-01-01',
    year: 1760,
    description: '英国开始工业革命，蒸汽机的发明和应用改变了生产方式。',
    category: '技术革命',
    importance: 'high',
    location: '英国',
    figures: ['詹姆斯·瓦特', '亚当·斯密'],
    relatedCards: [],
  },
  {
    id: 'event_16',
    title: '法国大革命',
    date: '1789-07-14',
    year: 1789,
    description: '法国人民攻占巴士底监狱，法国大革命正式开始。',
    category: '政治革命',
    importance: 'high',
    location: '法国巴黎',
    figures: ['路易十六', '玛丽·安托瓦内特', '罗伯斯庇尔'],
    relatedCards: [],
  },
  {
    id: 'event_17',
    title: '拿破仑称帝',
    date: '1804-12-02',
    year: 1804,
    description: '拿破仑·波拿巴在巴黎圣母院加冕为法国皇帝。',
    category: '政治变革',
    importance: 'high',
    location: '法国巴黎',
    figures: ['拿破仑·波拿巴'],
    relatedCards: [],
  },
  {
    id: 'event_18',
    title: '第一次世界大战开始',
    date: '1914-07-28',
    year: 1914,
    description: '奥匈帝国向塞尔维亚宣战，第一次世界大战爆发。',
    category: '世界战争',
    importance: 'high',
    location: '欧洲',
    figures: ['威廉二世', '弗朗茨·约瑟夫一世'],
    relatedCards: [],
  },
  {
    id: 'event_19',
    title: '俄国十月革命',
    date: '1917-11-07',
    year: 1917,
    description: '列宁领导布尔什维克党发动十月革命，推翻临时政府。',
    category: '政治革命',
    importance: 'high',
    location: '俄国彼得格勒',
    figures: ['列宁', '托洛茨基', '斯大林'],
    relatedCards: [],
  },
  {
    id: 'event_20',
    title: '第二次世界大战开始',
    date: '1939-09-01',
    year: 1939,
    description: '德国入侵波兰，第二次世界大战在欧洲正式开始。',
    category: '世界战争',
    importance: 'high',
    location: '波兰',
    figures: ['阿道夫·希特勒', '温斯顿·丘吉尔', '富兰克林·罗斯福'],
    relatedCards: [],
  },
];

// Sample historical periods
export const sampleTimelinePeriods: TimelinePeriod[] = [
  {
    id: 'period_1',
    name: '古代文明时期',
    startYear: -3000,
    endYear: 500,
    description: '人类早期文明的兴起，包括古埃及、古希腊、古罗马等伟大文明。',
    color: '#8B5A2B',
    events: sampleTimelineEvents.filter(e => e.year >= -3000 && e.year <= 500),
  },
  {
    id: 'period_2',
    name: '中世纪',
    startYear: 500,
    endYear: 1500,
    description: '欧洲中世纪时期，封建制度、基督教文化和伊斯兰文明的发展。',
    color: '#2E7D32',
    events: sampleTimelineEvents.filter(e => e.year >= 500 && e.year <= 1500),
  },
  {
    id: 'period_3',
    name: '近世时期',
    startYear: 1500,
    endYear: 1800,
    description: '文艺复兴、宗教改革、地理大发现和启蒙运动的时代。',
    color: '#1976D2',
    events: sampleTimelineEvents.filter(e => e.year >= 1500 && e.year <= 1800),
  },
  {
    id: 'period_4',
    name: '现代时期',
    startYear: 1800,
    endYear: 2024,
    description: '工业革命、民族国家兴起、两次世界大战和现代科技发展。',
    color: '#C62828',
    events: sampleTimelineEvents.filter(e => e.year >= 1800 && e.year <= 2024),
  },
];

// Function to generate timeline events from history cards
export function generateTimelineFromCards(cards: any[]): TimelineEvent[] {
  return cards
    .filter(card => card.historicalPeriod && card.historicalPeriod !== '未知')
    .map((card, index) => {
      // Extract year from historical period string
      const periodMatch = card.historicalPeriod.match(/(\d+)/);
      const year = periodMatch ? parseInt(periodMatch[0]) : new Date().getFullYear();

      return {
        id: `generated_${card.id}`,
        title: card.question.substring(0, 50) + (card.question.length > 50 ? '...' : ''),
        date: `${year}-01-01`,
        year: year,
        description: card.answer,
        category: card.category || '未分类',
        importance: card.difficulty === '困难' ? 'high' : card.difficulty === '中等' ? 'medium' : 'low',
        figures: card.keyFigures || [],
        relatedCards: [card.id],
      };
    })
    .sort((a, b) => a.year - b.year);
}