import { TimelineEvent, TimelinePeriod } from '@/types';

// Sample historical events data
export const sampleTimelineEvents: TimelineEvent[] = [
  {
    id: 'event_0',
    title: '农业革命开始',
    date: '-8000-01-01',
    year: -8000,
    description: '新石器时代农业革命开始，人类从狩猎采集转向农业定居，标志着文明的开端。主要作物包括小麦、大麦、稻米等。',
    category: '科技革命',
    importance: 'high',
    location: '美索不达米亚、中国、中美洲',
    figures: [],
    relatedCards: [],
  },
  {
    id: 'event_1',
    title: '胡夫大金字塔建造',
    date: '-2580-01-01',
    year: -2580,
    description: '古埃及第四王朝法老胡夫的陵墓，约公元前2580-2560年建造。原高146.5米，底边长230米，是古代世界七大奇迹中唯一现存的建筑。约用了250万块石块建成。',
    category: '古代建筑',
    importance: 'high',
    location: '埃及吉萨',
    figures: ['胡夫法老（库夫）', '海米乌努（建筑师）'],
    relatedCards: [],
    sources: [
      'Lehner, M. (1997). The Complete Pyramids. Thames & Hudson.',
      'Edwards, I.E.S. (1985). The Pyramids of Egypt. Penguin Books.',
      'Verner, M. (2001). The Pyramids: The Mystery, Culture, and Science of Egypt\'s Great Monuments. Grove Press.'
    ],
  },
  {
    id: 'event_2',
    title: '汉武帝即位',
    date: '-141-01-01',
    year: -141,
    description: '西汉第七位皇帝刘彻即位（公元前141年），在位54年。在位期间开疆拓土，派遣张骞通西域开辟丝绸之路，建立年号制度，推行推恩令削弱诸侯，是汉朝最强盛的时期。',
    category: '政治变革',
    importance: 'high',
    location: '中国长安',
    figures: ['汉武帝刘彻', '卫青', '霍去病', '张骞'],
    relatedCards: [],
  },
  {
    id: 'event_3',
    title: '罗马帝国建立',
    date: '-27-01-01',
    year: -27,
    description: '屋大维被元老院授予"奥古斯都"称号，标志着罗马共和国向罗马帝国的转变。',
    category: '政治变革',
    importance: 'high',
    location: '意大利罗马',
    figures: ['奥古斯都', '马克·安东尼', '克利奥帕特拉'],
    relatedCards: [],
    sources: [
      'Syme, R. (1939). The Roman Revolution. Oxford University Press.',
      'Gruen, E.S. (2005). Augustus and the Making of the Principate. In A Companion to the Roman Republic.',
      'Galinsky, K. (2012). Augustus: Introduction to the Life of an Emperor. Cambridge University Press.'
    ],
  },
  {
    id: 'event_4',
    title: '耶稣基督诞生',
    date: '-0004-01-01',
    year: -4,
    description: '基督教创始人耶稣基督的诞生。虽然公历以公元1年为起点，但现代学者普遍认为耶稣实际出生于公元前6-4年之间。',
    category: '宗教',
    importance: 'high',
    location: '犹太行省伯利恒',
    figures: ['耶稣基督', '圣母玛利亚', '约瑟'],
    relatedCards: [],
  },
  {
    id: 'event_5',
    title: '罗马帝国分裂',
    date: '395-01-01',
    year: 395,
    description: '狄奥多西一世死后，罗马帝国正式分裂为东西两部分。',
    category: '政治变革',
    importance: 'high',
    location: '罗马帝国',
    figures: ['狄奥多西一世', '阿卡狄乌斯', '霍诺里乌斯'],
    relatedCards: [],
  },
  {
    id: 'event_6',
    title: '唐朝建立',
    date: '618-01-01',
    year: 618,
    description: '李渊建立唐朝，定都长安，开启了中国历史上的黄金时代。',
    category: '政治变革',
    importance: 'high',
    location: '中国长安',
    figures: ['李渊', '李世民', '李建成'],
    relatedCards: [],
  },
  {
    id: 'event_7',
    title: '查理曼加冕',
    date: '800-12-25',
    year: 800,
    description: '法兰克国王查理曼在罗马被教皇利奥三世加冕为"罗马人的皇帝"。这一事件被视为神圣罗马帝国的开端，象征着基督教世界的政治统一。',
    category: '政治变革',
    importance: 'high',
    location: '意大利罗马',
    figures: ['查理曼大帝', '教皇利奥三世'],
    relatedCards: [],
  },
  {
    id: 'event_8',
    title: '北宋建立',
    date: '960-02-04',
    year: 960,
    description: '赵匡胤通过陈桥兵变（黄袍加身）建立宋朝，定都开封。结束了五代十国的分裂局面，开启了中国历史上科技文化繁荣的时代。',
    category: '政治变革',
    importance: 'high',
    location: '中国开封',
    figures: ['宋太祖赵匡胤', '赵普'],
    relatedCards: [],
  },
  {
    id: 'event_9',
    title: '十字军东征开始',
    date: '1095-11-27',
    year: 1095,
    description: '教皇乌尔班二世在克莱蒙会议上发起第一次十字军东征，号召基督教徒夺回耶路撒冷圣地，帮助拜占庭帝国抵御土耳其人。',
    category: '宗教战争',
    importance: 'high',
    location: '法国克莱蒙',
    figures: ['教皇乌尔班二世', '戈德弗里'],
    relatedCards: [],
  },
  {
    id: 'event_10',
    title: '蒙古帝国建立',
    date: '1206-01-01',
    year: 1206,
    description: '铁木真在斗里太訓召开库里台大会，被推举为蒙古部落的共同汗王，号成吉思汗，统一蒙古草原建立大蒙古国。',
    category: '政治变革',
    importance: 'high',
    location: '蒙古草原',
    figures: ['成吉思汗铁木真'],
    relatedCards: [],
  },
  {
    id: 'event_11',
    title: '黑死病大流行',
    date: '1347-01-01',
    year: 1347,
    description: '黑死病（鼠疫）从1347年起在欧洲大规模爆发，通过贸易路线传播。至少导致欧洲三分之一的人口死亡，对中世纪社会结构产生深远影响。',
    category: '灾难事件',
    importance: 'high',
    location: '欧洲',
    figures: [],
    relatedCards: [],
  },
  {
    id: 'event_12',
    title: '文艺复兴开始',
    date: '1400-01-01',
    year: 1400,
    description: '一场发源于意大利的文化运动，以14-16世纪为高峰。强调人文主义精神，重新发现古典希腊罗马文化，在艺术、文学、科学等领域取得巨大成就。',
    category: '文化运动',
    importance: 'high',
    location: '意大利佛罗伦萨',
    figures: ['达芬奇', '米开朗基罗', '拉斐尔'],
    relatedCards: [],
  },
  {
    id: 'event_13',
    title: '哥伦布发现美洲',
    date: '1492-10-12',
    year: 1492,
    description: '克里斯托弗·哥伦布到达美洲，开启了欧洲殖民美洲的时代。',
    category: '地理发现',
    importance: 'high',
    location: '加勒比海',
    figures: ['克里斯托弗·哥伦布'],
    relatedCards: [],
  },
  {
    id: 'event_14',
    title: '宗教改革开始',
    date: '1517-10-31',
    year: 1517,
    description: '马丁·路德发表《九十五条论纲》，开启了宗教改革运动。',
    category: '宗教改革',
    importance: 'high',
    location: '德国维滕堡',
    figures: ['马丁·路德'],
    relatedCards: [],
  },
  {
    id: 'event_15',
    title: '工业革命开始',
    date: '1760-01-01',
    year: 1760,
    description: '英国开始工业革命，蒸汽机的发明和应用改变了生产方式。',
    category: '技术革命',
    importance: 'high',
    location: '英国',
    figures: ['詹姆斯·瓦特', '亚当·斯密'],
    relatedCards: [],
  },
  {
    id: 'event_16',
    title: '法国大革命',
    date: '1789-07-14',
    year: 1789,
    description: '巴黎市民攻占巴士底监狱，这一事件成为法国大革命的象征性开端。巴士底被视为旧制度专制的象征，其被攻占代表着人民争取自由的意志。',
    category: '政治革命',
    importance: 'high',
    location: '法国巴黎',
    figures: ['路易十六', '玛丽·安托瓦内特', '罗伯斯庇尔'],
    relatedCards: [],
    sources: [
      'Schama, S. (1989). Citizens: A Chronicle of the French Revolution. Vintage Books.',
      'Doyle, W. (2001). The Oxford History of the French Revolution. Oxford University Press.',
      'Furet, F. (1981). Interpreting the French Revolution. Cambridge University Press.'
    ],
  },
  {
    id: 'event_17',
    title: '拿破仑称帝',
    date: '1804-12-02',
    year: 1804,
    description: '拿破仑在巴黎圣母院举行加冕典礼，成为法国皇帝。他亲手为自己戴上皇冠，象征着他的权力来源于自身而非教会。',
    category: '政治变革',
    importance: 'high',
    location: '法国巴黎',
    figures: ['拿破仑·波拿巴'],
    relatedCards: [],
  },
  {
    id: 'event_18',
    title: '第一次世界大战开始',
    date: '1914-07-28',
    year: 1914,
    description: '奥特列公爵弗朗茨·费迪南在萨拉热窩被刺，成为第一次世界大战的导火索。奥匈帝国向塞尔维亚宣战，各国同盟体系被激活，战争迅速扩大。',
    category: '世界战争',
    importance: 'high',
    location: '欧洲',
    figures: ['威廉二世', '弗朗茨·约瑟夫一世'],
    relatedCards: [],
  },
  {
    id: 'event_19',
    title: '俄国十月革命',
    date: '1917-11-07',
    year: 1917,
    description: '列宁领导的布尔什维克党在彼得格勒发动政变，推翻克伦斯基的临时政府，建立了世界上第一个社会主义国家。这引发了俄国内战。',
    category: '政治革命',
    importance: 'high',
    location: '俄国彼得格勒',
    figures: ['列宁', '托洛茨基', '斯大林'],
    relatedCards: [],
  },
  {
    id: 'event_20',
    title: '第二次世界大战开始',
    date: '1939-09-01',
    year: 1939,
    description: '德国入侵波兰，第二次世界大战在欧洲正式开始。',
    category: '世界战争',
    importance: 'high',
    location: '波兰',
    figures: ['阿道夫·希特勒', '温斯顿·丘吉尔', '富兰克林·罗斯福'],
    relatedCards: [],
  },
];

// Sample historical periods
export const sampleTimelinePeriods: TimelinePeriod[] = [
  {
    id: 'period_0',
    name: '史前时期',
    startYear: -8000,
    endYear: -3000,
    description: '农业革命开始，人类从狩猎采集转向农业定居，早期文明的萌芽。',
    color: '#6B7280',
    events: sampleTimelineEvents.filter(e => e.year >= -8000 && e.year <= -3000),
  },
  {
    id: 'period_1',
    name: '古代文明时期',
    startYear: -3000,
    endYear: 500,
    description: '人类早期文明的兴起，包括古埃及、古希腊、古罗马等伟大文明。',
    color: '#8B5A2B',
    events: sampleTimelineEvents.filter(e => e.year >= -3000 && e.year <= 500),
  },
  {
    id: 'period_2',
    name: '中世纪',
    startYear: 500,
    endYear: 1500,
    description: '欧洲中世纪时期，封建制度、基督教文化和伊斯兰文明的发展。',
    color: '#2E7D32',
    events: sampleTimelineEvents.filter(e => e.year >= 500 && e.year <= 1500),
  },
  {
    id: 'period_3',
    name: '近世时期',
    startYear: 1500,
    endYear: 1800,
    description: '文艺复兴、宗教改革、地理大发现和启蒙运动的时代。',
    color: '#1976D2',
    events: sampleTimelineEvents.filter(e => e.year >= 1500 && e.year <= 1800),
  },
  {
    id: 'period_4',
    name: '现代时期',
    startYear: 1800,
    endYear: 2024,
    description: '工业革命、民族国家兴起、两次世界大战和现代科技发展。',
    color: '#C62828',
    events: sampleTimelineEvents.filter(e => e.year >= 1800 && e.year <= 2024),
  },
];

// Function to generate timeline events from history cards
export function generateTimelineFromCards(cards: any[]): TimelineEvent[] {
  return cards
    .filter(card => card.historicalPeriod && card.historicalPeriod !== '未知')
    .map((card, index) => {
      // Extract year from historical period string
      const periodMatch = card.historicalPeriod.match(/(\d+)/);
      const year = periodMatch ? parseInt(periodMatch[0]) : new Date().getFullYear();

      return {
        id: `generated_${card.id}`,
        title: card.question.substring(0, 50) + (card.question.length > 50 ? '...' : ''),
        date: `${year}-01-01`,
        year: year,
        description: card.answer,
        category: card.category || '未分类',
        importance: (card.difficulty === 'Hard' ? 'high' : card.difficulty === 'Medium' ? 'medium' : 'low') as 'low' | 'medium' | 'high',
        figures: card.keyFigures || [],
        relatedCards: [card.id],
      };
    })
    .sort((a, b) => a.year - b.year);
}